### ISSUE TITLE
phenology labels

### ISSUE THREAD

**Issue by jeffmarti** [khufkens/snotelr#12]
Are the end of snow(EOS)/start of snow(SOS)labels on the phenology plot reversed?   I'm assuming that's what the acronyms refer to.   But I'm not totally sure.   Thanks.

![image](https://user-images.githubusercontent.com/46584819/51014981-2aef3500-151f-11e9-9682-d52c09f0050d.png)

**Comment by khufkens** [comment]
Thanks for finding this.

Fixed in:
https://github.com/khufkens/snotelr/commit/ac06358b7033a950912235f78c417e64c03c3038

+ some other colour issues in plotly.

Will not make it into a new CRAN release soon as only a minor issue. Use de development release until enough fixed accumulate for a new CRAN release.
