### ISSUE TITLE
first and last snow melt day of year capped at 179

### ISSUE THREAD

**Issue by jeffmarti** [khufkens/snotelr#24]
Hello, it looks like both the "first_snow_melt_doy" and "last_snow_melt_doy" values in the  SNOTEL phenology data are capped at DOY 179.   

You can also see the effects of this in the phenology plot below (site id 679).  Is this an error and am I missing something in the interpretation of the data?     Thank you. - Jeff

![image](https://github.com/bluegreen-labs/snotelr/assets/46584819/85bb7024-95cf-461d-a36d-246ecdbcabe7)

**Comment by khufkens** [comment]
This is an artefact of dealing with seasonality. The assumption is that the period DOY -180 to 180 captures both SOS and EOS. This most likely is a site at high latitude (Alaska?, didn't check) and snow melt can therefore be initiated very late. 

This should be fixed by increasing the window over which the stats are calculated. I should check the logic of the routine to see if just increasing this value does what it should do. Any pull request fixing this would be appreciated though, I'm rather tied up for now.

https://github.com/bluegreen-labs/snotelr/blob/356e557b1b408577def45f60420d91d97ab5d7af/R/snotel_phenology.r#L72

**Comment by khufkens** [comment]
This is now fixed by #26 in github version 1.3

Check https://github.com/bluegreen-labs/snotelr/blob/master/analysis/test_offset.R

for an example. I've not yet fixed the GUI to have a dynamic offset

**Comment by jeffmarti** [comment]
Thank you!
