### ISSUE TITLE
Where can I find the downloaded data?

### ISSUE THREAD

**Issue by tungmilan** [khufkens/snotelr#6]
Hello Koen,

Thanks for developing this package. Looks very great especially the shiny app!

I have trouble finding the downloaded data. Where can I find it within my workspace?

```
dat <- download.snotel(site = 1263)
> head(dat)
NULL
```

**Comment by khufkens** [comment]
Data is exported into your current working directory (set by the path parameter).

Sorry the help file is misleading, I should update the package.

**Comment by tungmilan** [comment]
Thanks @khufkens ! Can you make a similar function (e.g. `read.snotel`) that process the downloaded data into a data frame? It's more convenient for users as they don't have to read back the data into R.

**Comment by khufkens** [comment]
I'll try to pick the project back up again. I wrote the package mainly for a validation exercise of some Google Earth Engine code (https://github.com/khufkens/MCD10A1) and it has been a while since I worked on it - have to figure out what I did myself I fear. 

I will try to free up some time to create an "internal" parameter flag to export all downloaded data as a tidy data frame.

**Comment by tungmilan** [comment]
That would be great! Thanks @khufkens !
